--Hecho por Cayetano Verduzco Alejandro

--Tercer Semestre - Química 1.

--Temas Primer Parcial Química 1.
INSERT INTO Temas VALUES (150,151,'Materia y Energía'); 
INSERT INTO Temas VALUES (150,152,'Propiedades de la Materia'); 
INSERT INTO Temas VALUES (150,153,'Fenómemos Físicos y Químicos'); 
INSERT INTO Temas VALUES (150,154,'Elemento, Compuesto y Mezcla');  
INSERT INTO Temas VALUES (150,155,'Métodos de Separación de Mezclas'); 

--Temas Segundo Parcial Química 1.
INSERT INTO Temas VALUES (250,251,'El Átomo'); 
INSERT INTO Temas VALUES (250,252,'Números Cuánticos'); 
INSERT INTO Temas VALUES (250,253,'Tabulación de los Números Cuánticos'); 
INSERT INTO Temas VALUES (250,254,'Principio de Construcción o Aufbau'); 
INSERT INTO Temas VALUES (250,255,'Configuración Electrónica');
INSERT INTO Temas VALUES (250,256,'Construcción de la Tabla Periódica'); 
INSERT INTO Temas VALUES (250,257,'Propiedades Periódicas'); 
INSERT INTO Temas VALUES (250,258,'Propiedades de los Elementos de Transición'); 

--Temas Tercer Parcial Química 1.
INSERT INTO Temas VALUES (350,351,'Enlace Químico'); 
INSERT INTO Temas VALUES (350,352,'Nomenclatura Química Inorgánica'); 
INSERT INTO Temas VALUES (350,353,'Hidruros Metálicos');
INSERT INTO Temas VALUES (350,354,'Hidruros no Metálicos – Ácidos'); 
INSERT INTO Temas VALUES (350,355,'Sales Binarias');
INSERT INTO Temas VALUES (350,356,'Hidróxidos');

---Creación de Tabla para las Preguntas de Química 1.
CREATE TABLE PreguntasQ1( 
		ID_Tema INTEGER NOT NULL,
		ID_PreguntaQ1 INTEGER NOT NULL,
		Preguntas VARCHAR(400) NOT NULL,
		PRIMARY KEY(ID_PreguntaQ1),
		FOREIGN KEY(ID_Tema)
		REFERENCES Temas(ID_Tema)
		);

--Preguntas Primer Parcial Química 1.

--Tema 1 Materia y Energía
INSERT INTO PreguntasQ1 VALUES (151,01,'¿Qué entiendes por materia? a) Todo lo que ocupa un lugar en el espacio y tiene masa b) La cantidad de materia contenida en un objeto c) La energía asociada con un objeto en movimiento'),
(151,02,'¿Cuáles son las propiedades fundamentales de la materia? a) Masa y energía. b) Masa, volumen y temperatura. c) Masa, energía y espacio.'),
(151,03,'¿Qué es masa? a) La cantidad de materia contenida en un objeto. b) La fuerza con la que un objeto es atraído hacia la Tierra. c) La capacidad de un objeto para hacer trabajo.'),
(151,04,'¿Qué es energía? a) La capacidad de un objeto para hacer trabajo. b) La cantidad de espacio que ocupa un objeto. c) La fuerza con la que un objeto es atraído hacia la Tierra.'),
(151,05,'¿Cuál es el enunciado de la ley de la conservación de la masa o Ley de Lavoisier desde el punto de vista de la química. a) La masa de un sistema cerrado permanece constante con el tiempo, a medida que la materia no puede ser creada ni destruida, solo transformada en diferentes formas. b) La energía total de un sistema cerrado permanece constante con el tiempo, a medida que la energía no puede ser creada ni destruida, solo transformada en diferentes formas. c) La masa y la energía de un sistema cerrado permanecen constantes con el tiempo, ya que ambos no pueden ser creados ni destruidos, solo transformados en diferentes formas.'),
(151,06,'Enunciado de la ley de la conservación de la energía. a) La masa de un sistema cerrado permanece constante con el tiempo, a medida que la materia no puede ser creada ni destruida, solo transformada en diferentes formas. b) La energía total de un sistema cerrado permanece constante con el tiempo, a medida que la energía no puede ser creada ni destruida, solo transformada en diferentes formas. c) La masa y la energía de un sistema cerrado permanecen constantes con el tiempo, ya que ambos no pueden ser creados ni destruidos, solo transformados en diferentes formas.'),
(151,07,'Enunciado de la ley de la conservación de la masa-energía. a) La masa de un sistema cerrado permanece constante con el tiempo, a medida que la materia no puede ser creada ni destruida, solo transformada en diferentes formas. b) La energía total de un sistema cerrado permanece constante con el tiempo, a medida que la energía no puede ser creada ni destruida, solo transformada en diferentes formas. c) La masa y la energía de un sistema cerrado permanecen constantes con el tiempo, ya que ambos no pueden ser creados ni destruidos, solo transformados en diferentes formas.'),
(151,08,'¿Cuál es el concepto de energía potencial gravitacional? a) La energía asociada con la posición de un objeto en un campo gravitacional. b) La energía asociada con la velocidad de un objeto en movimiento. c) La energía asociada con la temperatura de un objeto.'),
(151,09,'¿Cuál es el concepto de energía potencial química? a) La energía asociada con la posición de un objeto en un campo gravitacional. b) La energía almacenada en los enlaces químicos de una sustancia. c) La energía asociada con la velocidad de un objeto en movimiento.'),
(151,10,'¿Cuál es el concepto de energía cinética? a) La energía asociada con la posición de un objeto en un campo gravitacional. b) La energía asociada con la velocidad de un objeto en movimiento. c) La energía almacenada en los enlaces químicos de una sustancia.');

--Tema 2 Propiedades de la Materia
INSERT INTO PreguntasQ1 VALUES (152,11,'¿Qué es propiedad general o común? a) Una característica que depende de la cantidad de materia presente. b) Una característica que no depende de la cantidad de materia presente. c) Una propiedad que solo se observa en ciertos tipos de sustancias.'),
(152,12,'¿Cuál es el concepto de peso? a) La masa de un objeto. b) La fuerza con la que un objeto es atraído hacia la Tierra. c) La cantidad de espacio que ocupa un objeto.'),
(152,13,'¿Cuál es el concepto de volumen? a) La masa de un objeto. b) La fuerza con la que un objeto es atraído hacia la Tierra. c) La cantidad de espacio que ocupa un objeto.'),
(152,14,'¿Cuál es el concepto de porosidad? a) La capacidad de un material para recuperar su forma original después de aplicarle una fuerza. b) La medida en que un material permite el paso de líquidos o gases a través de sus poros. c) La cantidad de materia en un determinado volumen.'),
(152,15,'¿Cuál es el concepto de divisibilidad? a) La capacidad de un material para recuperar su forma original después de aplicarle una fuerza. b) La capacidad de un material para ser dividido en partes más pequeñas. c) La medida en que un material permite el paso de líquidos o gases a través de sus poros.'),
(152,16,'¿Cuál es el concepto de inercia? a) La resistencia de un líquido a fluir. b) La tendencia de un objeto a permanecer en su estado de reposo o movimiento. c) La capacidad de un material para recuperar su forma original después de aplicarle una fuerza.'),
(152,17,'¿Cuál es el concepto de impenetrabilidad? a) La resistencia de un líquido a fluir. b) La tendencia de un objeto a permanecer en su estado de reposo o movimiento. c) La incapacidad de dos cuerpos ocupar el mismo lugar al mismo tiempo.'),
(152,18,'¿Cuál es el concepto de elasticidad? a) La capacidad de un material para recuperar su forma original después de aplicarle una fuerza. b) La medida en que un material permite el paso de líquidos o gases a través de sus poros. c) La resistencia de un líquido a fluir.'),
(152,19,'¿Qué es propiedad específica, particular o distintiva? a) Una característica que depende de la cantidad de materia presente. b) Una característica que no depende de la cantidad de materia presente. c) Una propiedad que solo se observa en ciertos tipos de sustancias.'),
(152,20,'¿Cuál es el concepto de densidad? a) La cantidad de espacio que ocupa un objeto. b) La relación entre la masa y el volumen de un objeto. c) La fuerza con la que un objeto es atraído hacia la Tierra.'),
(152,21,'¿Qué es el punto de ebullición? a) La temperatura a la cual un líquido se convierte en sólido. b) La temperatura a la cual un líquido hierve y se convierte en gas. c) La temperatura a la cual un sólido se convierte en líquido.'),
(152,22,'¿Qué es el punto de fusión? a) La temperatura a la cual un líquido se convierte en sólido. b) La temperatura a la cual un líquido hierve y se convierte en gas. c) La temperatura a la cual un sólido se convierte en líquido.'),
(152,23,'¿Cuál es el concepto de viscosidad? a) La resistencia de un líquido a fluir. b) La capacidad de un material para recuperar su forma original después de aplicarle una fuerza. c) La medida en que un material permite el paso de líquidos o gases a través de sus poros.'),
(152,24,'¿Cuál es el concepto de presión de vapor? a) La fuerza con la que un objeto es atraído hacia la Tierra. b) La presión ejercida por las moléculas de un líquido en equilibrio dinámico entre el líquido y su vapor. c) La medida en que un material permite el paso de líquidos o gases a través de sus poros.'),
(152,25,'¿Qué es propiedad extensiva? a) Una característica que depende de la cantidad de materia presente. b) Una característica que no depende de la cantidad de materia presente. c) Una propiedad que solo se observa en ciertos tipos de sustancias.'),
(152,26,'¿Qué es propiedad intensiva? a) Una característica que depende de la cantidad de materia presente. b) Una característica que no depende de la cantidad de materia presente. c) Una propiedad que solo se observa en ciertos tipos de sustancias.'),
(152,27,'El enunciado “Líquido que al combinarse con metales produce sustancias inflamables” es una propiedad específica: a) Química b) Física'),
(152,28,'El enunciado “Sólido cristalino púrpura, con densidad de 2.703g/mL, hierve a 260°C” es una propiedad específica: a) Química b) Física'),
(152,29,'El enunciado “Metal líquido plateado, inodoro, pesado y ligeramente volátil” es una propiedad específica: a) Química b) Física'),
(152,30,'El enunciado “Sustancia ácida empleada en el blanqueamiento de aceites, grasas y ceras” es una propiedad específica: a) Química b) Física'),
(152,31,'El enunciado “El trióxido de azufre gaseoso es un oxidante fuerte que acelera la combustión de algunas sustancias” es una propiedad específica: a) Química b) Física'),
(152,32,'Tipo de transformación de energía cuando tuestas un pan en estufa de gas. a) Eléctrica a mecánica b) Eléctrica a química c) Química a calorífica d) Solar a química'),
(152,33,'Tipo de transformación de energía en la fotosíntesis de las plantas. a) Eléctrica a mecánica b) Eléctrica a química c) Química a calorífica d) Solar a química'),
(152,34,'Tipo de transformación de energía cuando cargas un celular. a) Eléctrica a mecánica b) Eléctrica a química c) Química a calorífica d) Solar a química'),
(152,35,'Tipo de transformación de energía en una licuadora en funcionamiento. a) Eléctrica a mecánica b) Eléctrica a química c) Química a calorífica d) Solar a química');

--Tema 3 Fenómemos Físicos y Químicos
INSERT INTO PreguntasQ1 VALUES (153,36,'¿Qué es un fenómeno? a) Un evento natural observable b) Un concepto abstracto c) Una teoría científica'),
(153,37,'¿Cuántos tipos de fenómenos hay y cuáles son? a) Dos: físicos y químicos b) Tres: naturales, artificiales y sociales c) Cuatro: mecánicos, eléctricos, magnéticos y térmicos'),
(153,38,'¿Qué es un fenómeno físico? a) Un cambio en la composición de la materia b) Una transformación irreversible c) Una alteración en las propiedades de la materia sin cambiar su composición'),
(153,39,'¿Qué es un fenómeno químico? a) Un cambio en el estado físico de la materia b) Una transformación que no altera las propiedades de la materia c) Una reacción que produce un cambio en la composición de la materia'),
(153,40,'¿Cuántos y cuáles son los estados de agregación de la masa? a) Tres: sólido, líquido y gas b) Cuatro: sólido, líquido, gas y plasma c) Cinco: sólido, líquido, gas, plasma y coloidal'),
(153,41,'¿Cuáles son los nombres que reciben los diferentes cambios de estado de agregación? a) Fusión, solidificación, evaporación, condensación, sublimación y deposición b) Derretimiento, congelación, vaporización, licuefacción, sublimación inversa y cristalización c) Licuación, evaporación, congelación, fusión, solidificación y volatilización'),
(153,42,'¿En qué consiste la fusión? a) El paso de sólido a gas b) El paso de gas a sólido c) El paso de sólido a líquido'),
(153,43,'¿En qué consiste la solidificación? a) El paso de líquido a gas b) El paso de gas a líquido c) El paso de líquido a sólido'),
(153,44,'¿En qué consiste la evaporación? a) El paso de sólido a gas b) El paso de líquido a gas c) El paso de gas a líquido'),
(153,45,'¿En qué consiste la condensación? a) El paso de gas a líquido b) El paso de líquido a gas c) El paso de sólido a líquido'),
(153,46,'¿En qué consiste la sublimación? a) El paso de sólido a gas b) El paso de gas a sólido c) El paso de líquido a gas'),
(153,47,'¿En qué consiste la deposición? a) El paso de gas a sólido b) El paso de sólido a líquido c) El paso de líquido a sólido'),
(153,48,'¿En qué consiste la licuación o licuefacción? a) El paso de gas a líquido b) El paso de líquido a gas c) El paso de sólido a líquido'),
(153,49,'El encendido de un boiler de gas es un fenómeno: a) Físico b) Químico'),
(153,50,'Calentar agua en el horno de microondas es un fenómeno: a) Físico b) Químico'),
(153,51,'La preparación de plátanos fritos es un fenómeno: a) Físico b) Químico'),
(153,52,'La pulverización de la pimienta es un fenómeno: a) Físico b) Químico'),
(153,53,'El encendido de una luz de bengala es un fenómeno: a) Físico b) Químico'),
(153,54,'La maduración de las frutas es un fenómeno: a) Físico b) Químico'),
(153,55,'El cambio de estado cuando se seca el cabello es: a) Condensación b) Fusión c) Evaporación d) Solidificación'),
(153,56,'El cambio de estado en el enfriamiento de la lava es: a) Condensación b) Fusión c) Evaporación d) Solidificación'),
(153,57,'El cambio de estado en la formación de nubes es: a) Condensación b) Fusión c) Deposición d) Solidificación'),
(153,58,'El cambio de estado en la formación de magma volcánico es: a) Condensación b) Fusión c) Evaporación d) Solidificación'),
(153,59,'El cambio de estado de la parafina de una vela al estar encendida es: a) Condensación b) Fusión c) Evaporación d) Solidificación'),
(153,60,'El cambio de estado de la “Desaparición” del desodorante ambiental sólido es: a) Condensación b) Sublimación c) Evaporación d) Solidificación');

--Tema 4 Elemento, Compuesto y Mezcla
INSERT INTO PreguntasQ1 VALUES (154,61,'¿Cómo se clasifican las sustancias puras? a) Elementos y compuestos b) Metálicas y no metálicas c) Orgánicas e inorgánicas'),
(154,62,'¿Cuál es el concepto de elemento químico? a) Una sustancia formada por la combinación de átomos de diferentes elementos. b) Una sustancia que no puede descomponerse en sustancias más simples mediante una reacción química. c) Una sustancia compuesta por átomos de un solo tipo.'),
(154,63,'¿Cuál es el concepto de compuesto? a) Una sustancia formada por la combinación de átomos de diferentes elementos. b) Una sustancia que no puede descomponerse en sustancias más simples mediante una reacción química. c) Una sustancia compuesta por átomos de un solo tipo.'),
(154,64,'¿Qué es una mezcla? a) Una combinación de dos o más sustancias que no mantienen su identidad química. b) Una sustancia pura compuesta por átomos de diferentes elementos. c) Una combinación de dos o más sustancias que mantienen su identidad química.'),
(154,65,'¿Qué es una mezcla homogénea? a) Una mezcla en la que los componentes están uniformemente distribuidos y no se pueden distinguir a simple vista. b) Una mezcla en la que los componentes pueden separarse fácilmente. c) Una mezcla en la que los componentes forman fases separadas.'),
(154,66,'¿Qué es una mezcla heterogénea? a) Una mezcla en la que los componentes están uniformemente distribuidos y no se pueden distinguir a simple vista. b) Una mezcla en la que los componentes forman fases separadas. c) Una mezcla en la que los componentes pueden distinguirse fácilmente.'),
(154,67,'El tungsteno es un(a): a) Elemento b) Compuesto c) Mezcla'),
(154,68,'El bicarbonato de sodio es un(a): a) Elemento b) Compuesto c) Mezcla'),
(154,69,'La salsa Valentina es un(a): a) Elemento b) Compuesto c) Mezcla'),
(154,70,'El yoduro de calcio es un(a): a) Elemento b) Compuesto c) Mezcla'),
(154,71,'El bismuto es un(a): a) Elemento b) Compuesto c) Mezcla'),
(154,72,'La acetona es un(a): a) Elemento b) Compuesto c) Mezcla'),
(154,73,'Un dije de oro blanco es un(a): a) Elemento b) Compuesto c) Mezcla'),
(154,74,'El ácido acetilsalicílico es un(a): a) Elemento b) Compuesto c) Mezcla'),
(154,75,'La maruchan con camarón es una mezcla: a) Homogénea b) Heterogénea'),
(154,76,'El enjuague bucal es una mezcla: a) Homogénea b) Heterogénea'),
(154,77,'La sal con pimienta y perejil es una mezcla: a) Homogénea b) Heterogénea'),
(154,78,'El suero facial es una mezcla: a) Homogénea b) Heterogénea'),
(154,79,'El helado de chocolate con nuez es una mezcla: a) Homogénea b) Heterogénea'),
(154,80,'El agua infusionada de fresa es una mezcla: a) Homogénea b) Heterogénea'),
(154,81,'Una lámina de bronce es una mezcla: a) Homogénea b) Heterogénea'),
(154,82,'Las aceitunas en salmuera es una mezcla: a) Homogénea b) Heterogénea'),
(154,83,'La gasolina Magna es un(a): a) Elemento b) Compuesto c) Mezcla'),
(154,84,'Un anillo de rodio puro es un(a): a) Elemento b) Compuesto c) Mezcla'),
(154,85,'El cereal con leche es una mezcla: a) Homogénea b) Heterogénea');

--Tema 5 Métodos de Separación de Mezclas
INSERT INTO PreguntasQ1 VALUES (155,86,'¿En qué consiste la decantación? a) Es el proceso de separación de líquidos miscibles mediante la diferencia de densidades. b) Es el proceso de separación de sólidos insolubles en un líquido mediante la sedimentación. c) Es el proceso de separación de sólidos por tamaño de partícula.'),
(155,87,'¿En qué consiste la filtración? a) Es el proceso de separación de líquidos miscibles mediante la diferencia de densidades. b) Es el proceso de separación de sólidos insolubles en un líquido mediante un medio poroso. c) Es el proceso de separación de componentes de una mezcla basado en sus diferentes puntos de ebullición.'),
(155,88,'¿En qué consiste la centrifugación? a) Es el proceso de separación de líquidos miscibles mediante la diferencia de densidades. b) Es el proceso de separación de sólidos insolubles en un líquido mediante la sedimentación. c) Es el proceso de separación de componentes de una mezcla mediante la fuerza centrífuga.'),
(155,89,'¿En qué consiste la destilación? a) Es el proceso de separación de líquidos miscibles mediante la diferencia de densidades. b) Es el proceso de separación de sólidos insolubles en un líquido mediante la sedimentación. c) Es el proceso de separación de componentes de una mezcla basado en sus diferentes puntos de ebullición.'),
(155,90,'¿En qué consiste la cristalización? a) Es el proceso de separación de líquidos miscibles mediante la diferencia de densidades. b) Es el proceso de separación de sólidos insolubles en un líquido mediante la sedimentación. c) Es el proceso de separación de componentes de una mezcla mediante la formación de cristales a partir de la solución.'),
(155,91,'¿En qué consiste el método de separación por solubilidad? a) Es el proceso de separación de sólidos insolubles en un líquido mediante la sedimentación. b) Es el proceso de separación de componentes de una mezcla mediante la formación de cristales a partir de la solución. c) Es el proceso de separación de componentes de una mezcla basado en su diferente solubilidad en un solvente.'),
(155,92,'¿En qué consiste el método de separación por tamizado? a) Es el proceso de separación de sólidos por tamaño de partícula. b) Es el proceso de separación de componentes de una mezcla basado en su diferente solubilidad en un solvente. c) Es el proceso de separación de sólidos insolubles en un líquido mediante la sedimentación.'),
(155,93,'¿En qué consiste el método de separación por imantación? a) Es el proceso de separación de componentes de una mezcla mediante la formación de cristales a partir de la solución. b) Es el proceso de separación de sólidos insolubles en un líquido mediante la sedimentación. c) Es el proceso de separación de sólidos magnéticos de una mezcla utilizando un imán.'),
(155,94,'¿En qué consiste el método de separación por cromatografía? a) Es el proceso de separación de líquidos miscibles mediante la diferencia de densidades. b) Es el proceso de separación de componentes de una mezcla basado en su diferente solubilidad en un solvente. c) Es el proceso de separación de componentes de una mezcla mediante la migración diferencial a través de una fase estacionaria.'),
(155,95,'Se tiene una mezcla de arena y limaduras de hierro. ¿Qué método de separación se debe utilizar? a) Filtración b) Decantación c) Imantación'),
(155,96,'Una mezcla de sal y arena se puede separar utilizando: a) Destilación b) Cristalización c) Tamizado'),
(155,97,'¿Cuál es el método más adecuado para separar una mezcla de aceite y agua? a) Decantación b) Centrifugación c) Filtración'),
(155,98,'Se necesita separar una mezcla de tinta y agua. ¿Qué método sería más efectivo? a) Evaporación b) Decantación c) Cromatografía'),
(155,99,'¿Qué técnica de separación se utilizaría para separar una mezcla de gasolina y agua? a) Decantación b) Destilación c) Cristalización'),
(155,100,'¿Cuál es el método adecuado para separar una mezcla de azúcar y arena? a) Filtración b) Decantación c) Tamizado'),
(155,101,'Para separar una mezcla de acetona y agua, ¿qué método sería más apropiado? a) Destilación b) Decantación c) Cristalización'),
(155,102,'¿Qué método se utiliza para separar una mezcla de hierro y azufre? a) Imantación b) Decantación c) Evaporación'),
(155,103,'Se necesita separar una mezcla de azufre y arena. ¿Cuál sería el método más eficaz? a) Imantación b) Tamizado c) Decantación'),
(155,104,'Para separar una mezcla de alcohol y agua, ¿cuál sería el método más adecuado? a) Destilación b) Centrifugación c) Filtración'),
(155,105,'¿Qué método se utilizaría para separar una mezcla de tinta y papel? a) Filtración b) Cromatografía c) Evaporación'),
(155,106,'¿Cuál es el método apropiado para separar una mezcla de sal y agua? a) Decantación b) Cristalización c) Destilación'),
(155,107,'¿Qué técnica de separación se utilizaría para separar una mezcla de mercurio y agua? a) Filtración b) Decantación c) Imantación'),
(155,108,'¿Cuál es el método más efectivo para separar una mezcla de azúcar y agua? a) Filtración b) Cristalización c) Decantación'),
(155,109,'¿Qué técnica de separación se utilizaría para separar una mezcla de gasolina y arena? a) Decantación b) Tamizado c) Destilación'),
(155,110,'Se dispone de una mezcla de cloruro de sodio (sal común) y ácido benzoico. ¿Cuál sería el método más apropiado para separar los componentes de esta mezcla? a) Filtración b) Destilación fraccionada c) Sublimación');


--Preguntas Segundo Parcial Química 1.

--Tema 1 El Átomo
INSERT INTO PreguntasQ1 VALUES (251,111,'¿Qué es el átomo? a) La unidad básica de la materia que forma todos los elementos químicos. b) Una partícula subatómica con carga positiva. c) Una partícula subatómica con carga negativa.'),
(251,112,'¿Qué es el electrón? a) Una partícula subatómica con carga positiva. b) Una partícula subatómica con carga negativa. c) La unidad básica de la materia que forma todos los elementos químicos.'),
(251,113,'¿Cuáles son dos características del electrón? a) Tiene una masa aproximadamente igual a la del protón y reside en el núcleo del átomo. b) Tiene una masa muy pequeña y orbita alrededor del núcleo en regiones llamadas niveles de energía. c) Es una partícula neutra y no participa en las reacciones químicas.'),
(251,114,'¿Qué es el protón? a) Una partícula subatómica con carga negativa. b) Una partícula subatómica con carga positiva. c) La unidad básica de la materia que forma todos los elementos químicos.'),
(251,115,'¿Cuáles son dos características del protón? a) Tiene una masa muy pequeña y orbita alrededor del núcleo en regiones llamadas niveles de energía. b) Tiene una masa aproximadamente igual a la del electrón y reside en el núcleo del átomo. c) Es una partícula neutra y no participa en las reacciones químicas.'),
(251,116,'¿Qué es el neutrón? a) Una partícula subatómica con carga negativa. b) Una partícula subatómica con carga positiva. c) Una partícula subatómica sin carga eléctrica.'),
(251,117,'¿Cuáles son dos características del neutrón? a) Tiene una masa aproximadamente igual a la del protón y reside en el núcleo del átomo. b) Es una partícula neutra y no participa en las reacciones químicas. c) Tiene una masa muy pequeña y orbita alrededor del núcleo en regiones llamadas niveles de energía.'),
(251,118,'¿Qué es el número atómico? a) La suma de protones y neutrones en el núcleo de un átomo. b) El número total de electrones en un átomo. c) El número de protones en el núcleo de un átomo, que determina el elemento químico.'),
(251,119,'¿Qué es el número de masa? a) La suma de protones y neutrones en el núcleo de un átomo. b) El número total de electrones en un átomo. c) El número de protones en el núcleo de un átomo, que determina el elemento químico.'),
(251,120,'¿Qué es un isótopo? a) Átomos de un mismo elemento con el mismo número de protones pero diferente número de neutrones. b) Átomos de diferentes elementos con el mismo número de protones pero diferente número de neutrones. c) Átomos de un mismo elemento con el mismo número de neutrones pero diferente número de protones.'),
(251,121,'¿Cuáles son los isótopos del carbono? a) Carbono-12, carbono-13 y carbono-14. b) Carbono-10, carbono-11 y carbono-12. c) Carbono-13, carbono-14 y carbono-15.'),
(251,122,'¿Cuáles son los isótopos del uranio? a) Uranio-234, uranio-235 y uranio-238. b) Uranio-230, uranio-232 y uranio-235. c) Uranio-235, uranio-236 y uranio-238.'),
(251,123,'¿Qué es la masa atómica? a) La masa total de un átomo, que es la suma de protones y neutrones en su núcleo. b) La masa de un átomo, medida en kilogramos. c) La masa promedio de un átomo de un elemento, considerando todos sus isótopos y su abundancia relativa.'),
(251,124,'Si el Berilio tiene un número másico de 9, ¿cuántos protones, neutrones y electrones tiene respectivamente? a) 4 protones, 9 neutrones, 4 electrones. b) 4 protones, 5 neutrones, 4 electrones. c) 9 protones, 4 neutrones, 9 electrones.'),
(251,125,'Si el Manganeso posee 30 neutrones, ¿cuál es su número atómico, másico, de protones y electrones, respectivamente? a) Número atómico: 30, Número másico: 25, Protones: 30, Electrones: 30. b) Número atómico: 30, Número másico: 55, Protones: 55, Electrones: 30. c) Número atómico: 25, Número másico: 55, Protones: 25, Electrones: 25.'),
(251,126,'Si el Hierro tiene un número másico de 56 y 26 electrones, ¿cuál es su número atómico, de protones y neutrones, respectivamente? a) Número atómico: 26, Protones: 56, Neutrones: 30. b) Número atómico: 30, Protones: 26, Neutrones: 56. c) Número atómico: 56, Protones: 26, Neutrones: 30.'),
(251,127,'Si el Silicio tiene 14 neutrones y 14 electrones, ¿cuál es su número atómico, másico y de protones, respectivamente? a) Número atómico: 14, Número másico: 14, Protones: 14. b) Número atómico: 14, Número másico: 28, Protones: 14. c) Número atómico: 14, Número másico: 28, Protones: 28.'),
(251,128,'Si el Oro tiene un número atómico de 79 y 118 neutrones, ¿cuál es su número másico, de protones y de electrones, respectivamente? a) Número másico: 118, Protones: 79, Electrones: 79. b) Número másico: 197, Protones: 118, Electrones: 79. c) Número másico: 197, Protones: 79, Electrones: 118.'),
(251,129,'Si el Antimonio tiene un número atómico de 51 y un número másico de 122, ¿cuál es su número de protones, neutrones y electrones, respectivamente? a) Protones: 51, Neutrones: 71, Electrones: 51. b) Protones: 71, Neutrones: 51, Electrones: 71. c) Protones: 122, Neutrones: 51, Electrones: 51.'),
(251,130,'Si el Rubidio tiene un número atómico de 37 y un número másico de 85, ¿cuál es su número de protones, neutrones y electrones, respectivamente? a) Protones: 85, Neutrones: 37, Electrones: 37. b) Protones: 37, Neutrones: 48, Electrones: 37. c) Protones: 37, Neutrones: 48, Electrones: 85.'),
(251,131,'¿Cuántos electrones, protones y neutrones contiene respectivamente un átomo cuyo número de masa es de 101 y número atómico 44? a) Electrones: 101, Protones: 101, Neutrones: 44. b) Electrones: 44, Protones: 101, Neutrones: 57. c) Electrones: 44, Protones: 44, Neutrones: 57.'),
(251,132,'¿Cuántos electrones, protones y neutrones contiene respectivamente un átomo cuyo número de masa es 50 y número atómico 25? a) Electrones: 25, Protones: 25, Neutrones: 25. b) Electrones: 50, Protones: 25, Neutrones: 25. c) Electrones: 25, Protones: 25, Neutrones: 50.'),
(251,133,'¿Cuántos electrones, protones y neutrones contiene respectivamente un átomo cuyo número de masa es 72 y número atómico 36? a) Electrones: 72, Protones: 72, Neutrones: 36. b) Electrones: 36, Protones: 36, Neutrones: 72. c) Electrones: 36, Protones: 36, Neutrones: 36.'),
(251,134,'¿Cuántos electrones, protones y neutrones contiene respectivamente un átomo cuyo número de masa es 60 y número atómico 28? a) Electrones: 28, Protones: 60, Neutrones: 28. b) Electrones: 28, Protones: 28, Neutrones: 32. c) Electrones: 60, Protones: 60, Neutrones: 32.'),
(251,135,'¿Cuántos electrones, protones y neutrones contiene respectivamente un átomo cuyo número de masa es 207 y número atómico 82? a) Electrones: 125, Protones: 207, Neutrones: 82. b) Electrones: 82, Protones: 125, Neutrones: 207. c) Electrones: 82, Protones: 82, Neutrones: 207.');

--Tema 2 Números Cuánticos
INSERT INTO PreguntasQ1 VALUES (252,136,'¿Qué plantea el Principio de Incertidumbre de Heisenberg? a) La imposibilidad de conocer con precisión la posición y la cantidad de movimiento de una partícula al mismo tiempo. b) La relación entre la energía y la frecuencia de una partícula. c) La estructura discreta de los niveles de energía en un átomo.'),
(252,137,'¿Qué es lo que permiten conocer las diferentes soluciones de la ecuación de onda planteada por Schrödinger? a) La forma de la trayectoria de una partícula en un campo eléctrico. b) La distribución de la densidad de probabilidad de encontrar una partícula en un determinado espacio. c) La velocidad de una partícula en un campo magnético.'),
(252,138,'¿Cuáles son los números cuánticos que se obtuvieron de la ecuación de onda? a) Principal (n) y secundario (ℓ). b) Azimutal (ℓ) y magnético (m). c) Principal (n), secundario (ℓ), magnético (m) y de espín (ms).'),
(252,139,'¿A qué hace referencia el cuarto número cuántico planteado por Samuel Goudsmit y George Eugene Uhlenbeck? a) A la dirección de espín de un electrón en un orbital. b) A la orientación espacial de un orbital en el espacio. c) A la orientación de un electrón en un campo magnético.'),
(252,140,'¿Qué representa el número cuántico principal "n"? a) La forma del orbital. b) La energía del electrón. c) La distancia promedio del electrón al núcleo.'),
(252,141,'¿Cuáles son los valores posibles que puede asumir el número cuántico principal "n"? a) Enteros positivos mayores que 1. b) Enteros positivos mayores o iguales que 0. c) Enteros positivos mayores que 0.'),
(252,142,'¿Qué representa el número cuántico secundario azimutal o de momento angular "ℓ"? a) La forma del orbital. b) La energía del electrón. c) La orientación espacial del orbital.'),
(252,143,'¿Cómo se determinan los valores del número cuántico secundario? a) Por medio de ecuaciones matemáticas complejas. b) Por medio de experimentos de dispersión de partículas. c) Por medio de la ecuación de onda y reglas cuánticas.'),
(252,144,'¿Qué literal específica se le asigna a cada uno de los valores de "ℓ“? a) s, p, d, f. b) 0, 1, 2, 3. c) m.'),
(252,145,'¿Qué representa el número cuántico magnético "m"? a) La forma del orbital. b) La energía del electrón. c) La orientación espacial del orbital en un campo magnético.'),
(252,146,'¿Cómo se determinan los valores de “m”? a) Son determinados por el número cuántico principal. b) Son determinados por el número cuántico secundario. c) Son determinados por el número cuántico azimutal.'),
(252,147,'¿Qué representa el número cuántico spin "ms" o “s”? a) La dirección del movimiento orbital de un electrón. b) La orientación del espín del electrón en un orbital. c) La energía total del electrón en un orbital.'),
(252,148,'¿Cuáles son los posibles valores de ms o “s”? a) -1/2 y +1/2. b) -1 y 1. c) 0 y 1.'),
(252,149,'¿Qué es un orbital? a) La trayectoria circular de un electrón alrededor del núcleo. b) La región del espacio donde es probable encontrar un electrón. c) La ubicación exacta de un electrón dentro de un átomo.'),
(252,150,'¿Cuál es la diferencia entre nivel, subnivel y orbital? a) Son términos intercambiables. b) Un nivel contiene varios subniveles, y un subnivel contiene varios orbitales. c) Un subnivel contiene varios niveles, y un orbital contiene varios subniveles.'),
(252,151,'¿Cuántos números cuánticos posee un electrón? a) 2 b) 3 c) 4'),
(252,152,'Los posibles valores de "ℓ" en el tercer nivel energético son: a) 0 y 1 b) 0, 1 y 2 c) 1 y 2'),
(252,153,'Los valores que puede asumir el número magnético, para ℓ=2, son: a) -2, -1, 0, +1, +2 b) -1, 0, 1 c) 0, +1, +2'),
(252,154,'El número máximo de electrones en el cuarto nivel energético, son: a) 16 b) 32 c) 18'),
(252,155,'El número de orbitales en el primer y segundo nivel energético, son respectivamente: a) 1 y 2 b) 2 y 4 c) 2 y 8'),
(252,156,'¿Cuántos valores del número cuántico "m" se tienen, cuando ℓ=2? a) 2 b) 3 c) 5'),
(252,157,'Si el número cuántico "m" presenta 7 valores, ¿A qué subnivel corresponde? a) “s” b) “f” c) “d”'),
(252,158,'En un átomo hay un nivel de energía para el cual el valor del número cuántico principal es igual a 4. ¿Cuántos valores tiene "m"? a) 2 b) 3 c) 7'),
(252,159,'En un átomo hay un nivel de energía para el cual n=4. ¿Cuáles son los valores de "ℓ"? a) 0, 1, 2, 3 b) 0, 1, 2 c) 0, 1, 2, 3'),
(252,160,'¿Cuántos subniveles hay en el segundo y cuarto nivel energético, respectivamente? a) 2 y 4 b) 3 y 8 c) 4 y 16');

--Tema 3 Tabulación de los Números Cuánticos
INSERT INTO PreguntasQ1 VALUES (253,161,'¿Cuántos subniveles existen en el nivel 1? a) 2 b) 4 c)1 d) 3'),
(253,162,'¿Cuántos subniveles existen en el nivel 2? a) 2 b) 4 c)1 d) 3'),
(253,163,'¿Cuántos subniveles existen en el nivel 3? a) 2 b) 4 c)1 d) 3'),
(253,164,'¿Cuántos subniveles existen en el nivel 4? a) 2 b) 4 c)1 d) 3'),
(253,165,'¿Cuántos orbitales existen en el subnivel ℓ=0, s? a) 5 b) 1 c) 3 d) 7'),
(253,166,'¿Cuántos orbitales existen en el subnivel ℓ=1, p? a) 5 b) 1 c) 3 d) 7'),
(253,167,'¿Cuántos orbitales existen en el subnivel ℓ=2, d? a) 5 b) 1 c) 3 d) 7'),
(253,168,'¿Cuántos orbitales existen en el subnivel ℓ=3, f? a) 5 b) 1 c) 3 d) 7'),
(253,169,'¿Cuántos electrones existen por orbital? a) 1 b) 3 c) 2'),
(253,170,'¿Cuántos orbitales existen en el nivel n=1? a) 9 b) 16 c) 4 d)1'),
(253,171,'¿Cuántos orbitales existen en el nivel n=2? a) 9 b) 16 c) 4 d)1'),
(253,172,'¿Cuántos orbitales existen en el nivel n=3? a) 9 b) 16 c) 4 d)1'),
(253,173,'¿Cuántos orbitales existen en el nivel n=4? a) 9 b) 16 c) 4 d)1'),
(253,174,'¿Cuántos electrones existen en el subnivel ℓ=0, s? a) 10 b) 2 c) 6 d) 14'),
(253,175,'¿Cuántos electrones existen en el subnivel ℓ=1, p? a) 10 b) 2 c) 6 d) 14'),
(253,176,'¿Cuántos electrones existen en el subnivel ℓ=2, d? a) 10 b) 2 c) 6 d) 14'),
(253,177,'¿Cuántos electrones existen en el subnivel ℓ=3, f? a) 10 b) 2 c) 6 d) 14'),
(253,178,'¿Cuántos electrones totales existen en el nivel n=1? a) 2 b) 18 c) 8 d) 32'),
(253,179,'¿Cuántos electrones totales existen en el nivel n=2? a) 2 b) 18 c) 8 d) 32'),
(253,180,'¿Cuántos electrones totales existen en el nivel n=3? a) 2 b) 18 c) 8 d) 32'),
(253,181,'¿Cuántos electrones totales existen en el nivel n=4? a) 2 b) 18 c) 8 d) 32'),
(253,182,'¿Cuál es la fórmula para calcular las orbitales por nivel? a) n2 b) 2(2ℓ+1) c) 2n2'),
(253,183,'¿Cuál es la fórmula para calcular los electrones totales por nivel? a) n2 b) 2(2ℓ+1) c) 2n2'),
(253,184,'¿Cuál es la fórmula para calcular los electrones por subnivel? a) n2 b) 2(2ℓ+1) c) 2n2');

--Tema 4 Principio de Construcción o Aufbauv
INSERT INTO PreguntasQ1 VALUES (254,185,'¿Qué es el estado basal del átomo? a) El estado con el mayor número de electrones. b) El estado de menor energía de un átomo con todos los electrones en los orbitales de menor energía. c) El estado con la mayor cantidad de energía.'),
(254,186,'¿Qué no dice el enunciado del principio de exclusión de Pauli? a) Dos electrones en un átomo no pueden tener los mismos valores de los cuatro números cuánticos. b) Solo puede haber un electrón por orbital en un átomo. c) Los electrones en un átomo tienden a ocupar los orbitales de menor energía primero.'),
(254,187,'¿Qué no dice el principio de edificación progresiva o regla de Aufbau? a) Los electrones llenan los orbitales comenzando por los de menor energía hasta alcanzar los de mayor energía. b) Dos electrones en un átomo no pueden tener los mismos valores de los cuatro números cuánticos. c) Cada orbital puede contener un máximo de dos electrones con espines opuestos.'),
(254,188,'¿Qué no dice el concepto de traslape energético? a) La superposición de orbitales atómicos que resulta en la formación de orbitales moleculares en enlaces químicos. b) Los electrones en un átomo tienden a ocupar los orbitales de menor energía primero. c) La tendencia de los electrones a ocupar orbitales de igual energía antes de emparejarse.');

--Tema 5 Configuración Electrónica
INSERT INTO PreguntasQ1 VALUES (255,189,'¿Cuál es el principio de máxima multiplicidad o regla de Hund? a) Los electrones llenan los orbitales comenzando por los de menor energía hasta alcanzar los de mayor energía. b) Los electrones en un átomo tienden a ocupar orbitales de igual energía antes de emparejarse y con espines paralelos. c) Dos electrones en un átomo no pueden tener los mismos valores de los cuatro números cuánticos.'),
(255,190,'¿Qué es la configuración electrónica? a) La representación gráfica de la distribución de los electrones en los orbitales atómicos de un átomo. b) La combinación de los números cuánticos para describir el estado de un electrón en un átomo. c) El número total de electrones en un átomo.'),
(255,191,'¿Qué es el electrón diferencial? a) El último electrón que ingresa a una distribución electrónica. b) El electrón con mayor energía en un átomo. c) El primer electrón que ingresa a una distribución.'),
(255,192,'¿Cuáles son los cuatro números cuánticos del átomo con número atómico 35? a) n=3, ℓ=1, m=0, ms=1/2 b) n=3, ℓ=0, m=0, ms=1/2 c) n=4, ℓ=1, m=0, ms=-1/2'),
(255,193,'¿Cuáles son los cuatro números cuánticos del átomo con número atómico 82? a) n=6, ℓ=2, m=0, ms=1/2 b) n=6, ℓ=0, m=0, ms=-1/2 c) n=6, ℓ=1, m=0, ms=+1/2'),
(255,194,'¿Cuáles son los cuatro números cuánticos del átomo con número atómico 42? a) n=5, ℓ=0, m=0, ms=-1/2 b) n=4, ℓ=2, m=1, ms=1/2 c) n=4, ℓ=1, m=0, ms=-1/2'),
(255,195,'¿Cuáles son los cuatro números cuánticos del átomo con número atómico 78? a) n=5, ℓ=2, m=0, ms=-1/2 b) n=6, ℓ=2, m=0, ms=-1/2 c) n=6, ℓ=1, m=0, ms=+1/2'),
(255,196,'¿Cuáles son los cuatro números cuánticos del átomo con número atómico 48? a) n=5, ℓ=1, m=0, ms=1/2 b) n=4, ℓ=2, m=0, ms=-1/2 c) n=4, ℓ=2, m=+2, ms=-1/2'),
(255,197,'¿Cuántos electrones tiene el elemento con números cuánticos “n=3, ℓ=1, m=+1, ms=+1/2”? a) 13 b) 15 c) 14'),
(255,198,'¿Cuántos electrones tiene el elemento con números cuánticos “n=5, ℓ=2, m=0, ms=+1/2”? a) 72 b) 73 c) 75'),
(255,199,'¿Cuántos electrones tiene el elemento con números cuánticos “n=5, ℓ=1, m=-1, ms=-1/2”? a) 52 b) 54 c) 53'),
(255,200,'¿Cuántos electrones tiene el elemento con números cuánticos “n=4, ℓ=2, m=+2, ms=-1/2”? a) 46 b) 47 c) 48'),
(255,201,'¿Cuántos electrones tiene el elemento con números cuánticos “n=3, ℓ=0, m=0, ms=+1/2”? a) 11 b) 13 c) 12');

--Tema 6 Construcción de la Tabla Periódica
INSERT INTO PreguntasQ1 VALUES (256,202,'¿Qué es un período en la tabla periódica? a) Una fila horizontal que indica el número de capas de electrones. b) Una columna vertical que indica el número de electrones en un átomo. c) Una fila vertical que indica la ubicación de un elemento específico.'),
(256,203,'¿Cómo se determina el período en que se localiza un elemento dado, a partir de su configuración electrónica? a) Contando el número de electrones en la capa más externa. b) Contando el número de electrones en la capa más interna. c) Contando el número de electrones en todas las capas del átomo.'),
(256,204,'¿Qué es una clase o bloque en la tabla periódica? a) Una columna vertical que indica la ubicación de un elemento específico. b) Un grupo de elementos que tienen propiedades químicas similares. c) Una fila horizontal que indica el número de capas de electrones.'),
(256,205,'¿Cómo determinar si un elemento es representativo o principal, de transición o de transición interna, a partir de su configuración electrónica? a) Observando el número de electrones de valencia. b) Observando el número de electrones de las capas internas. c) Observando el número de electrones en la capa más externa.'),
(256,206,'¿Qué es un grupo en la tabla periódica? a) Una fila horizontal que indica el número de capas de electrones. b) Una columna vertical que indica el número de electrones en un átomo. c) Una columna vertical que indica la ubicación de un elemento específico.'),
(256,207,'¿Cómo determinar el grupo al que pertenece un elemento en la Tabla periódica, a partir de su configuración electrónica y de sus electrones de valencia? a) Observando el número de capas de electrones. b) Observando el número de electrones en la capa más externa. c) Observando el número de electrones en las capas internas.'),
(256,208,'¿Qué es una familia en la tabla periódica? a) Un grupo de elementos que tienen propiedades químicas similares. b) Una columna vertical que indica la ubicación de un elemento específico. c) Una fila horizontal que indica el número de capas de electrones.'),
(256,209,'¿Cómo clasificar a un elemento, a partir de su nombre, como alcalino, alcalinotérreo, halógeno o gas noble, con ayuda de la tabla periódica? a) Observando su posición en la tabla periódica. b) Observando el número de protones en el núcleo. c) Observando el número de electrones en la capa más externa.'),
(256,210,'¿Cómo se construye la Tabla periódica a partir de la configuración electrónica de los átomos? a) Organizando los elementos en filas y columnas según el número de protones en el núcleo. b) Organizando los elementos en filas y columnas según el número de electrones en la capa más externa. c) Organizando los elementos en filas y columnas según el número de neutrones en el núcleo.'),
(256,211,'¿Cuál es el bloque “s” de la tabla periódica? a) Representativo b) Transición c) Transición interna'),
(256,212,'¿Cuál es el bloque “p” de la tabla periódica? a) Representativo b) Transición c) Transición interna'),
(256,213,'¿Cuál es el bloque “d” de la tabla periódica? a) Representativo b) Transición c) Transición interna'),
(256,214,'¿Cuál es el bloque “f” de la tabla periódica? a) Representativo b) Transición c) Transición interna');

--Tema 7 Propiedades Periódicas
INSERT INTO PreguntasQ1 VALUES (257,215,'¿Cuál es la Ley Periódica de Mendeleiev? a) Los elementos están ordenados según su número atómico. b) Los elementos están ordenados según su masa atómica. c) Los elementos están ordenados según sus propiedades químicas, en función de su número atómico.'),
(257,216,'¿Cuál es la Ley Periódica de Moseley? a) Los elementos están ordenados según su número atómico. b) Los elementos están ordenados según su masa atómica. c) Los elementos están ordenados según sus propiedades químicas, en función de su número de electrones.'),
(257,217,'¿Qué es el radio atómico? a) La distancia entre el núcleo del átomo y su capa de valencia. b) La distancia entre el núcleo del átomo y su electrón más externo. c) La distancia entre dos átomos adyacentes en una molécula.'),
(257,218,'¿Qué es la energía de ionización? a) La energía necesaria para remover un electrón de un átomo neutro. b) La energía necesaria para añadir un electrón a un átomo neutro. c) La energía liberada cuando un átomo se combina con otro para formar un enlace químico.'),
(257,219,'¿Qué es la afinidad electrónica? a) La energía necesaria para remover un electrón de un átomo neutro. b) La energía liberada cuando un átomo gana un electrón. c) La tendencia de un átomo a ceder electrones.'),
(257,220,'¿Qué es la electronegatividad? a) La energía necesaria para remover un electrón de un átomo neutro. b) La capacidad de un átomo para atraer electrones hacia sí mismo en un enlace químico. c) La tendencia de un átomo a perder electrones.'),
(257,221,'¿Qué es la Valencia? a) El número de protones en el núcleo de un átomo. b) La capacidad de un átomo para formar enlaces químicos. c) La cantidad de electrones en la capa de valencia de un átomo.'),
(257,222,'¿Qué es el número de oxidación? a) La carga eléctrica total de un átomo en un compuesto. b) El número de electrones en la capa de valencia de un átomo. c) La capacidad de un átomo para atraer electrones hacia sí mismo.'),
(257,223,'¿Qué son los electrones periféricos? a) Los electrones en las capas más internas de un átomo. b) Los electrones en la capa de valencia de un átomo. c) Los electrones en las capas más externas de un átomo.'),
(257,224,'¿Qué es la actividad química metálica? a) La tendencia de un elemento a ganar electrones. b) La tendencia de un elemento a perder electrones. c) La tendencia de un elemento a formar enlaces metálicos.'),
(257,225,'¿Qué es la actividad química no metálica? a) La tendencia de un elemento a ganar electrones. b) La tendencia de un elemento a perder electrones. c) La tendencia de un elemento a formar enlaces iónicos.'),
(257,226,'¿Cuáles son algunas características de los elementos de transición? a) Tienen configuraciones electrónicas completas. b) Tienen una gran variedad de estados de oxidación. c) Tienen una baja densidad y punto de fusión.'),
(257,227,'¿Cómo se saben los electrones de valencia de los elementos representativos? a) Observando su número atómico. b) Observando su posición en la tabla periódica. c) Observando su configuración electrónica.');

--Tema 8 Propiedades de los Elementos de Transición
INSERT INTO PreguntasQ1 VALUES (258,228,'¿Qué son los iones coloridos? a) Iones que presentan una carga eléctrica nula. b) Iones que absorben y emiten luz visible. c) Iones que son neutros en condiciones estándar.'),
(258,229,'¿Qué son los iones complejos? a) Iones que presentan una carga eléctrica nula. b) Iones que consisten en un átomo central rodeado por moléculas o iones llamados ligandos. c) Iones que tienen una alta afinidad por los electrones.'),
(258,230,'¿Qué es la actividad catalítica? a) La tendencia de un elemento a ganar electrones. b) La capacidad de un catalizador para acelerar una reacción química sin ser consumido en ella. c) La tendencia de un elemento a perder electrones.'),
(258,231,'¿Qué es el magnetismo y paramagnetismo? a) La capacidad de un material para ser atraído por un imán. b) La tendencia de un material a no ser afectado por un campo magnético. c) La capacidad de un material para generar un campo magnético propio cuando se coloca en un campo magnético externo.'),
(258,232,'¿A qué se debe la variabilidad de los números de oxidación en los elementos de transición? a) A su capacidad para ganar electrones. b) A su configuración electrónica parcialmente llena en diferentes orbitales. c) A su tendencia a formar enlaces iónicos.');

--Preguntas Tercer Parcial Química.

--Tema 1 Enlace Químico
INSERT INTO PreguntasQ1 VALUES (351,233,'¿Qué es el enlace químico? a) La atracción entre dos átomos que comparten electrones. b) La unión entre dos o más átomos mediante la transferencia o compartición de electrones. c) La repulsión entre dos átomos cargados positivamente.'),
(351,234,'¿Qué es una molécula? a) Una partícula cargada eléctricamente. b) La unidad más pequeña de un compuesto que conserva sus propiedades químicas. c) Una combinación de átomos de diferentes elementos.'),
(351,235,'¿Cuáles son los tipos de enlace químico que existen? a) Enlace iónico, enlace covalente y enlace metálico. b) Enlace primario, enlace secundario y enlace terciario. c) Enlace intramolecular, enlace intermolecular y enlace covalente.'),
(351,236,'¿Qué es la regla del octeto? a) Los átomos tienden a ganar, perder o compartir electrones para adquirir una configuración electrónica completa con ocho electrones en su capa de valencia. b) Los átomos tienden a formar ocho enlaces químicos en una molécula. c) Los átomos tienden a tener ocho electrones en su núcleo.'),
(351,237,'¿En qué consiste el enlace iónico? a) En la transferencia de electrones entre dos átomos. b) En el compartimiento de electrones entre dos átomos. c) En la repulsión de electrones entre dos átomos.'),
(351,238,'¿Cómo se denominan a las especies resultantes de la transferencia de electrones al formarse el enlace iónico? a) Moléculas. b) Iones. c) Electrones.'),
(351,239,'¿Cómo se denomina a la especie química que se produce al donar electrones? a) Cationes. b) Aniones. c) Neutrones.'),
(351,240,'¿Cómo se denomina a la especie química que se produce al aceptar electrones? a) Cationes. b) Aniones. c) Neutrones.'),
(351,241,'¿Cuál es la fórmula condensada del compuesto iónico resultante de la unión química del Cesio y bromo? a) CsBr b) BrCs c) Cs2Br'),
(351,242,'¿Cuál es la fórmula condensada del compuesto iónico resultante de la unión química del Rubidio y oxígeno? a) RbO b) RO c) Rb2O'),
(351,243,'¿En qué consiste el enlace covalente? a) En la transferencia de electrones entre dos átomos. b) En el compartimiento de electrones entre dos átomos. c) En la repulsión de electrones entre dos átomos.'),
(351,244,'Con base en la diferencia de electronegatividad ¿Cómo se clasifica al enlace covalente? a) Polar y apolar. b) Metálico y no metálico. c) Iónico y metálico.'),
(351,245,'¿Cuál es la fórmula condensada del compuesto covalente resultante de la unión química del Radio y fósforo? a) RaP b) PRa c) Ra3P2'),
(351,246,'¿Cuál la fórmula condensada del compuesto covalente resultante de la unión química del litio y selenio? a) LiSe b) SeLi c) Li2Se3'),
(351,247,'El compuesto PH3 tiene un tipo de enlace: a) Iónico b) Covalente polar c) Covalente no polar d) Covalente puro'),
(351,248,'El compuesto NaF tiene un tipo de enlace: a) Iónico b) Covalente polar c) Covalente no polar d) Covalente puro'),
(351,249,'El compuesto AsCl3 tiene un tipo de enlace: a) Iónico b) Covalente polar c) Covalente no polar d) Covalente puro'),
(351,250,'El compuesto CS2 tiene un tipo de enlace: a) Iónico b) Covalente polar c) Covalente no polar d) Covalente puro'),
(351,251,'El compuesto Ba3N2 tiene un tipo de enlace: a) Iónico b) Covalente polar c) Covalente no polar d) Covalente puro'),
(351,252,'El compuesto I2 tiene un tipo de enlace: a) Iónico b) Covalente polar c) Covalente no polar d) Covalente puro'),
(351,253,'El compuesto H2S tiene un tipo de enlace: a) Iónico b) Covalente polar c) Covalente no polar d) Covalente puro'),
(351,254,'El compuesto N2O3 tiene un tipo de enlace: a) Iónico b) Covalente polar c) Covalente no polar d) Covalente puro'),
(351,255,'¿Cuál es la fórmula condensada del compuesto covalente resultante de la unión química del Radio y fósforo? a) RaP b) Ra3P2 c) Ra2P3'),
(351,256,'¿Cuál es la fórmula condensada del compuesto covalente resultante de la unión química del Potasio y oxígeno? a) K2O b) KO c) K3O2'),
(351,257,'¿Cuál es la fórmula condensada del compuesto covalente resultante de la unión química del Carbono e hidrógeno? a) CH b) CH2 c) CH4'),
(351,258,'¿Cuál es la fórmula condensada del compuesto covalente resultante de la unión química del Nitrógeno y oxígeno? a) NO b) N2O c) NO2'),
(351,259,'¿Cuál es la fórmula condensada del compuesto covalente resultante de la unión química del Cloro y flúor? a) ClF b) Cl2F c) ClF3'),
(351,260,'¿Cuál es la fórmula condensada del compuesto covalente resultante de la unión química del Azufre y oxígeno? a) SO b) SO2 c) SO3'),
(351,261,'¿Cuál es la fórmula condensada del compuesto covalente resultante de la unión química del Hidrógeno y cloro? a) HCl b) H2Cl c) HCl3'),
(351,262,'¿Cuál es la fórmula condensada del compuesto covalente resultante de la unión química del Litio y oxígeno? a) LiO b) Li2O c) LiO2'),
(351,263,'¿Cuál es la fórmula condensada del compuesto covalente resultante de la unión química del Magnesio y nitrógeno? a) MgN b) Mg3N2 c) Mg2N3'),
(351,264,'¿Cuál es la fórmula condensada del compuesto covalente resultante de la unión química del Boro e hidrógeno? a) BH b) BH2 c) BH3'),
(351,265,'¿Qué es un octeto expandido? a) Una configuración electrónica en la que un átomo tiene más de ocho electrones en su capa de valencia. b) Una configuración electrónica en la que un átomo tiene menos de ocho electrones en su capa de valencia. c) Una configuración electrónica en la que un átomo tiene exactamente ocho electrones en su capa de valencia.'),
(351,266,'¿Qué es la carga formal? a) La carga eléctrica total de un átomo en un compuesto. b) La carga eléctrica de un átomo en una molécula, asumiendo que los electrones compartidos se dividen por igual entre los átomos unidos. c) La carga eléctrica de un átomo cuando gana o pierde electrones en una reacción química.'),
(351,267,'¿Cómo se calcula la carga formal? a) Se resta el número de electrones de valencia del átomo en su estado neutral del número de electrones asignados al átomo en la molécula. b) Se suma el número de electrones de valencia del átomo en su estado neutral al número de electrones asignados al átomo en la molécula. c) Se divide el número de electrones de valencia del átomo en su estado neutral entre el número de electrones asignados al átomo en la molécula.'),
(351,268,'Con base en el enlace covalente ¿Qué propiedades presentan las sustancias? a) Bajas temperaturas de fusión y ebullición, y son conductores de electricidad en estado líquido. b) Altas temperaturas de fusión y ebullición, y son buenos conductores de electricidad en estado sólido. c) Bajas temperaturas de fusión y ebullición, y son malos conductores de electricidad en cualquier estado.'),
(351,269,'¿Qué es el enlace covalente coordinado o dativo? a) Un tipo de enlace en el que dos átomos comparten un par de electrones de manera desigual. b) Un tipo de enlace en el que un átomo contribuye con ambos electrones del par compartido. c) Un tipo de enlace en el que los átomos tienen una alta electronegatividad.'),
(351,270,'Con ayuda de la tabla de electronegatividades, determina el tipo de enlace del compuesto: NaCl. a) Enlace iónico. b) Enlace covalente polar. c) Enlace covalente no polar.'),
(351,271,'Con ayuda de la tabla de electronegatividades, determina el tipo de enlace del compuesto: H2O. a) Enlace iónico. b) Enlace covalente polar. c) Enlace covalente no polar.'),
(351,272,'Con ayuda de la tabla de electronegatividades, determina el tipo de enlace del compuesto: Na2CO3. a) Enlace iónico. b) Enlace covalente polar. c) Enlace covalente no polar.'),
(351,273,'¿Qué es hibridación? a) El proceso por el cual se forman nuevos orbitales atómicos a partir de la combinación de orbitales puros. b) El proceso por el cual se forman enlaces químicos entre átomos. c) El proceso por el cual se forma una molécula a partir de átomos diferentes.'),
(351,274,'¿Qué es la hibridación sp? a) Hibridación que ocurre cuando un átomo utiliza un orbital s y un orbital p para formar dos orbitales híbridos. b) Hibridación que ocurre cuando un átomo utiliza tres orbitales s para formar tres orbitales híbridos. c) Hibridación que ocurre cuando un átomo utiliza un orbital s y tres orbitales p para formar cuatro orbitales híbridos.'),
(351,275,'¿Qué es la hibridación sp2? a) Hibridación que ocurre cuando un átomo utiliza un orbital s y dos orbitales p para formar tres orbitales híbridos. b) Hibridación que ocurre cuando un átomo utiliza un orbital s y tres orbitales p para formar cuatro orbitales híbridos. c) Hibridación que ocurre cuando un átomo utiliza dos orbitales s y dos orbitales p para formar cuatro orbitales híbridos.'),
(351,276,'¿Qué es la hibridación sp3? a) Hibridación que ocurre cuando un átomo utiliza un orbital s y tres orbitales p para formar cuatro orbitales híbridos. b) Hibridación que ocurre cuando un átomo utiliza un orbital s y un orbital p para formar dos orbitales híbridos. c) Hibridación que ocurre cuando un átomo utiliza dos orbitales s y dos orbitales p para formar cuatro orbitales híbridos.'),
(351,277,'¿A qué se llama estado excitado del átomo? a) Al estado en el que los electrones están en los niveles de energía más bajos. b) Al estado en el que los electrones están en los niveles de energía más altos. c) Al estado en el que los electrones están en los niveles de energía intermedios.'),
(351,278,'¿Cuál es la diferencia entre un enlace polar y la polaridad de una molécula? a) Un enlace polar implica una distribución desigual de carga a lo largo del enlace, mientras que la polaridad de una molécula se refiere a la distribución de cargas eléctricas en toda la molécula. b) Un enlace polar se forma por la transferencia de electrones entre átomos, mientras que la polaridad de una molécula se relaciona con la diferencia de electronegatividad entre los átomos. c) Un enlace polar se forma por la compartición desigual de electrones entre átomos, mientras que la polaridad de una molécula se refiere a la suma de todas las cargas eléctricas en la molécula.'),
(351,279,'¿En qué consiste el enlace metálico? a) Es un tipo de enlace en el que los átomos comparten electrones de manera desigual. b) Es un tipo de enlace en el que los átomos están unidos por puentes de hidrógeno. c) Es un tipo de enlace en el que los electrones se desplazan libremente entre los átomos.'),
(351,280,'¿Cuáles son las propiedades físicas de los metales? a) Son duros, frágiles y tienen un alto punto de fusión. b) Son maleables, dúctiles y tienen un brillo característico. c) Son gases a temperatura ambiente y tienen baja conductividad eléctrica.'),
(351,281,'¿En qué consiste el enlace por puente de hidrógeno? a) Es un tipo de enlace covalente en el que un átomo de hidrógeno forma un enlace con un átomo más electronegativo. b) Es un tipo de enlace en el que se comparten electrones entre dos átomos de hidrógeno. c) Es un tipo de enlace débil que se forma entre un átomo de hidrógeno unido a un átomo de nitrógeno, oxígeno o flúor y otro átomo de estos mismos elementos.'),
(351,282,'¿Cuáles son las propiedades del agua derivadas del tipo de enlace por puente de hidrógeno? a) El agua es un gas a temperatura ambiente y tiene baja densidad. b) El agua tiene una alta tensión superficial, un elevado calor específico y es un solvente polar excelente. c) El agua es una sustancia no polar y no puede formar enlaces de hidrógeno.'),
(351,283,'La molécula BeCl2 es: a) Simétrica b) Asimétrica'),
(351,284,'La molécula AlCl3 es: a) Simétrica b) Asimétrica'),
(351,285,'La molécula SiH4 es: a) Simétrica b) Asimétrica'),
(351,286,'La molécula CO2 es: a) Simétrica b) Asimétrica'),
(351,287,'La molécula H2O es: a) Simétrica b) Asimétrica'),
(351,288,'La molécula NH3 es: a) Simétrica b) Asimétrica'),
(351,289,'La molécula CH4 es: a) Simétrica b) Asimétrica'),
(351,290,'La molécula PH3 es: a) Polar b) No polar'),
(351,291,'La molécula H2S es: a) Polar b) No polar'),
(351,292,'La molécula HBr es: a) Polar b) No polar'),
(351,293,'La molécula CH4 es: a) Polar b) No polar'),
(351,294,'La molécula CO2 es: a) Polar b) No polar'),
(351,295,'La molécula CCl4 es: a) Polar b) No polar'),
(351,296,'La molécula SF6 es: a) Polar b) No polar');

--Tema 2 Nomenclatura Química Inorgánica
INSERT INTO PreguntasQ1 VALUES (352,297,'¿Qué es la nomenclatura química? a) Es el estudio de los nombres de los compuestos químicos. b) Es el estudio de la composición de los elementos químicos. c) Es el estudio de las propiedades químicas de los compuestos.'),
(352,298,'¿Cuáles son los tres tipos de nomenclatura que vemos en la academia? a) Nomenclatura binaria, nomenclatura orgánica y nomenclatura inorgánica. b) Nomenclatura sistemática, nomenclatura tradicional y nomenclatura Stock. c) Nomenclatura Stock, nomenclatura composicional y nomenclatura orgánica.'),
(352,299,'¿Cuáles son las características de la nomenclatura Tradicional? a) Utiliza prefijos numéricos para indicar la cantidad de átomos presentes. b) Utiliza el nombre del catión seguido por el del anión. c) Utiliza nombres comunes para los compuestos químicos.'),
(352,300,'¿Cuáles son las características de la nomenclatura Stock? a) Indica los números de oxidación de los elementos presentes en el compuesto. b) Utiliza nombres comunes basados en la estructura de la molécula. c) Utiliza el nombre del catión seguido por el del anión y entre paréntesis indica la carga del catión.'),
(352,301,'¿Cuáles son las características de la nomenclatura Composicional? a) Indica la composición exacta de los átomos presentes en el compuesto. b) Utiliza prefijos numéricos para indicar la cantidad de átomos presentes. c) Utiliza nombres comunes basados en las propiedades del compuesto.'),
(352,302,'¿Cuáles son los posibles números de oxidación en el grupo IA? a) 1+ b) 2+ c) 1-'),
(352,303,'¿Cuáles son los posibles números de oxidación en el grupo IIA? a) 1+ b) 2+ c) 3+'),
(352,304,'¿Cuáles son los posibles números de oxidación en el grupo IIIA? a) 1+ b) 2+ c) 3+'),
(352,305,'¿Cuáles son los posibles números de oxidación en el grupo IVA? a) 4+,2+,1- b) 4+,1-,4- c) 4+,2+,4-'),
(352,306,'¿Cuáles son los posibles números de oxidación en el grupo VA? a) 5+,3+,2+,3- b) 5+,3+,1+,3- c) 5+,3+,1+,1-'),
(352,307,'¿Cuáles son los posibles números de oxidación en el grupo VIA? a) 6+,4+,2+,2- b) 6+,3+,1+,2- c) 6+,4+,3+,3-'),
(352,308,'¿Cuáles son los posibles números de oxidación en el grupo VIIA? a) 7+,5+,3+,2+,1- b) 7+,5+,3+,2+,2- c) 7+,5+,3+,1+,1-'),
(352,309,'¿Cuáles son los posibles números de oxidación del cobre? a) +1, +2 b) +2, +3 c) +1, +3'),
(352,310,'¿Cuáles son los posibles números de oxidación del oro? a) +1, +2 b) +2, +3 c) +1, +3'),
(352,311,'¿Cuáles son los posibles números de oxidación de la plata? a) +1 b) +2 c) +3'),
(352,312,'¿Cuáles son los posibles números de oxidación del zinc? a) +1 b) +3 c) +2'),
(352,313,'¿Cuáles son los posibles números de oxidación del cadmio? a) +3 b) +2 c) +4'),
(352,314,'¿Cuáles son los posibles números de oxidación del mercurio? a) +1, +2 b) +2, +3 c) +1, +4'),
(352,315,'¿Cuáles son los posibles números de oxidación del cromo? a) -2, +3, +6 b) +2, +4, +6 c) +2, +3, +6'),
(352,316,'¿Cuáles son los posibles números de oxidación del hierro? a) +2, +3 b) +2, +4 c) +3, +4'),
(352,317,'¿Cuáles son los posibles números de oxidación del cobalto? a) +2, +3 b) +2, +4 c) +3, +4'),
(352,318,'¿Cuáles son los posibles números de oxidación del níquel? a) +2, +4 b) +2, +3 c) +3, +4');

--Tema 3 Hidruro Metálicos
INSERT INTO PreguntasQ1 VALUES (353,319,'¿Cómo está conformado un Hidruro Metálico? a) H+X- b)M+X- c) M+H- d) M+(OH)-'),
(353,320,'¿Cuál es el nombre del compuesto AlH3 en nomenclatura tradicional? a) Hidruro de aluminio b) Aluminio hidruro c) Trihidruro de aluminio'),
(353,321,'¿Cuál es el nombre del compuesto CuH2 en nomenclatura tradicional? a) Hidruro cuproso (I) b) Hidruro de cobre (II) c) Hidruro cúprico'),
(353,322,'¿Cuál es el nombre del compuesto PbH4 en nomenclatura tradicional? a) Hidruro plumboso b) Hidruro plúmbico c) Tetrahidruro de plomo'),
(353,323,'¿Cuál es el nombre del compuesto AlH3 en nomenclatura Stock? a) Hidruro de aluminio (I) b) Hidruro de Aluminio (III) c) Aluminio trihidruro'),
(353,324,'¿Cuál es el nombre del compuesto CuH2 en nomenclatura Stock? a) Hidruro de cobre (I) b) Hidruro de Cobre (II) c) Cobre dihidruro'),
(353,325,'¿Cuál es el nombre del compuesto PbH4 en nomenclatura Stock? a) Hidruro de plomo (II) b) Hidruro de Plomo (IV) c) Tetrahidruro de Plomo'),
(353,326,'¿Cuál es el nombre del compuesto AlH3 en nomenclatura composicional? a) Aluminio-trihidrógeno b) Trihidruro de aluminio c) Aluminio hidrógeno'),
(353,327,'¿Cuál es el nombre del compuesto CuH2 en nomenclatura composicional? a) Cobre-dihidrógeno b) Dihidruro de cobre c) Cobre hidrógeno'),
(353,328,'¿Cuál es el nombre del compuesto PbH4 en nomenclatura composicional? a) Plomo-tetrahidrógeno b) Tetrahidruro de plomo c) Plomo de hidrógeno'),
(353,329,'¿Cuál es la fórmula del Hidruro de francio? a) FrH b) FrH2 c) FrH3'),
(353,330,'¿Cuál es la fórmula del Trihidruro de níquel? a) NiH b) NiH2 c) NiH3'),
(353,331,'¿Cuál es la fórmula del Hidruro férrico? a) FeH b) FeH2 c) FeH3'),
(353,332,'¿Cuál es la fórmula del Hidruro de paladio (IV)? a) PdH b) PdH2 c) PdH4'),
(353,333,'¿Cuál es la fórmula del Dihidruro de calcio? a) CaH b) CaH2 c) CaH3'),
(353,334,'¿Cuál es la fórmula del Hidruro auroso? a) AuH b) AuH2 c) AuH3');

--Tema 4 Hidruros no Metálicos - Ácidos
INSERT INTO PreguntasQ1 VALUES (354,335,'¿Cómo está conformado un ácido? a) H+X- b)M+X- c) M+H- d) M+(OH)-'),
(354,336,'¿Cuál es la fórmula correcta del ácido clorhídrico? a) HCl b) HCl2 c) H2Cl'),
(354,337,'¿Cuál es la fórmula correcta del ácido bromhídrico? a) HBr2 b) HBr c) H2Br'),
(354,338,'¿Cuál es la fórmula correcta del ácido yodhídrico? a) H2I b) HI2 c) HI'),
(354,339,'¿Cuál es la fórmula correcta del ácido fluorhídrico? a) HF2 b) HF c) H2F'),
(354,340,'¿Cuál es la fórmula correcta del ácido sulfhídrico? a) HS b) H2S c) H2SO3'),
(354,341,'¿Cuál es la fórmula correcta del ácido selenhídrico? a) H2Se3 b) HSe c) H2Se'),
(354,342,'¿Cuál es la fórmula correcta del ácido telurhídrico? a) H2Te b) HTe c) H2TeO3'),
(354,343,'¿Cuál es el nombre correcto para el compuesto HBr? a) Ácido bromhídrico b) Bromuro de hidrógeno c) Hidróxido de bromo'),
(354,344,'¿Cuál es el nombre correcto para el compuesto H2S? a) Ácido sulfhídrico b) Sulfuro de hidrógeno c) Hidruro de azufre'),
(354,345,'¿Cuál es el nombre correcto para el compuesto HCl? a) Ácido clorhídrico b) Cloruro de hidrógeno c) Hidruro de cloro'),
(354,346,'¿Cuál es el nombre correcto para el compuesto H2Se? a) Ácido selenhídrico b) Seleniuro de hidrógeno c) Hidruro de selenio'),
(354,347,'¿Cuál es el nombre correcto para el compuesto H2Te? a) Ácido telurhídrico b) Telururo de hidrógeno c) Hidruro de telurio');

--Tema 5 Sales Binarias 
INSERT INTO PreguntasQ1 VALUES (355,348,'¿Cómo está conformada una sal binaria? a) H+X- b)M+X- c) M+H- d) M+(OH)-'),
(355,349,'¿Cuál es la fórmula correcta para el cloruro de sodio? a) NaCl b) Na2Cl c) NaCl2'),
(355,350,'¿Cuál es la fórmula correcta para el bromuro de potasio? a) K2Br b) KBr c) KBr2'),
(355,351,'¿Cuál es la fórmula correcta para el sulfuro de magnesio? a) MgS2 b) Mg2S c) MgS'),
(355,352,'¿Cuál es la fórmula correcta para el cloruro de zinc (II)? a) ZnCl2 b) ZnCl c) Zn2Cl3'),
(355,353,'¿Cuál es la fórmula correcta para el bromuro de hierro (III)? a) FeBr b) FeBr3 c) Fe3Br2'),
(355,354,'¿Cuál es la fórmula correcta para el sulfuro de cobre (II)? a) CuS2 b) Cu2S c) CuS'),
(355,355,'¿Cuál es la fórmula correcta para el cloruro de aluminio? a) AlCl3 b) AlCl c) Al2Cl3'),
(355,356,'¿Cuál es la fórmula correcta para el yoduro de potasio? a) KI2 b) KI c) K2I'),
(355,357,'¿Cuál es la fórmula correcta para el sulfuro de calcio? a) CaS b) Ca2S c) CaS2'),
(355,358,'¿Cuál es la nomenclatura correcta para la fórmula K3N? a) Nitrógeno de potasio b) Nitruro de potasio c) Nitruro tricálcico'),
(355,359,'¿Cuál es la nomenclatura correcta para la fórmula MgCl2? a) Cloruro de magnesio b) Cloruro magnésico c) Cloruro de dimagnesio'),
(355,360,'¿Cuál es la nomenclatura correcta para la fórmula CuBr? a) Bromuro de cobre (I) b) Bromuro de cobre (II) c) Bromuro cúprico'),
(355,361,'¿Cuál es la nomenclatura correcta para la fórmula Al2S3? a) Sulfuro de aluminio b) Aluminio trisulfuro c) Sulfuro dialuminoso'),
(355,362,'¿Cuál es la nomenclatura correcta para la fórmula Ca3N2? a) Nitruro de calcio b) Trinitruro de calcio c) Nitruro cálcico'),
(355,363,'¿Cuál es la nomenclatura correcta para la fórmula HgCl2? a) Cloruro de mercurio (I) b) Cloruro de mercurio (II) c) Cloruro de mercurioso');

--Tema 6 Hidróxidos
INSERT INTO PreguntasQ1 VALUES (356,364,'¿Cómo está conformado un hidróxido? a) H+X- b)M+X- c) M+H- d) M+(OH)-'),
(356,365,'¿Cuál es la fórmula correcta para el hidróxido de sodio? a) NaOH b) Na2OH c) Na(OH)2'),
(356,366,'¿Cuál es la fórmula correcta para el hidróxido de calcio? a) CaOH b) Ca(OH)2 c) Ca2OH'),
(356,367,'¿Cuál es la fórmula correcta para el hidróxido de magnesio? a) MgOH b) Mg(OH)2 c) Mg2OH'),
(356,368,'¿Cuál es la fórmula correcta para el hidróxido de hierro (III)? a) FeOH3 b) Fe(OH)3 c) Fe2(OH)3'),
(356,369,'¿Cuál es la fórmula correcta para el hidróxido de aluminio? a) AlOH b) Al(OH)2 c) Al(OH)3'),
(356,370,'¿Cuál es la fórmula correcta para el hidróxido de zinc? a) ZnOH b) Zn(OH)2 c) Zn2OH'),
(356,371,'¿Cuál es la fórmula correcta para el hidróxido de potasio? a) KOH b) K(OH)2 c) K2OH'),
(356,372,'¿Cuál es la fórmula correcta para el hidróxido de plata? a) AgOH b) Ag(OH)2 c) Ag2OH'),
(356,373,'¿Cuál es la fórmula correcta para el hidróxido de plomo (II)? a) PbOH2 b) Pb(OH)2 c) Pb2(OH)2'),
(356,374,'¿Cuál es la nomenclatura correcta para la fórmula NaOH? a) Hidróxido de sodio b) Oxihidróxido de sodio c) Hidróxido monosódico'),
(356,375,'¿Cuál es la nomenclatura correcta para la fórmula Ca(OH)2? a) Hidróxido de calcio b) Oxihidróxido de calcio c) Hidróxido bicálcico'),
(356,376,'¿Cuál es la nomenclatura correcta para la fórmula Mg(OH)2? a) Hidróxido de magnesio b) Oxihidróxido de magnesio c) Hidróxido dimagnésico'),
(356,377,'¿Cuál es la nomenclatura correcta para la fórmula Fe(OH)3? a) Hidróxido de hierro (III) b) Trihidróxido de hierro c) Hidróxido férrico'),
(356,378,'¿Cuál es la nomenclatura correcta para la fórmula Al(OH)3? a) Hidróxido de aluminio b) Oxihidróxido de aluminio c) Hidróxido tríaluminio'),
(356,379,'¿Cuál es la nomenclatura correcta para la fórmula Zn(OH)2? a) Hidróxido de zinc b) Oxihidróxido de zinc c) Hidróxido di-zincoso'),
(356,380,'¿Cuál es la nomenclatura correcta para la fórmula KOH? a) Hidróxido de potasio b) Oxihidróxido de potasio c) Hidróxido monopotásico');

--Creación de Tabla para las Respuetas de Química 1
CREATE TABLE RespuestasQ1(
		ID_PreguntaQ1 INTEGER NOT NULL,
		ID_RespuestaQ1 INTEGER NOT NULL,
		Respuestas VARCHAR(5) NOT NULL,
		PRIMARY KEY(ID_RespuestaQ1),
		FOREIGN KEY(ID_PreguntaQ1)
		REFERENCES PreguntasQ1(ID_PreguntaQ1)
		);		

--Respuestas Primer Parcial Química 1

--Tema 1 Materia y Energía
INSERT INTO RespuestasQ1 VALUES (01,010,'a'),
(02,020,'b'),
(03,030,'a'),
(04,040,'a'),
(05,050,'a'),
(06,060,'b'),
(07,070,'c'),
(08,080,'a'),
(09,090,'b'),
(10,100,'b');

--Tema 2 Propiedades de la Materia
INSERT INTO RespuestasQ1 VALUES (11,110,'b'),
(12,120,'b'),
(13,130,'c'),
(14,140,'b'),
(15,150,'b'),
(16,160,'b'),
(17,170,'c'),
(18,180,'a'),
(19,190,'b'),
(20,200,'b'),
(21,210,'b'),
(22,220,'c'),
(23,230,'a'),
(24,240,'b'),
(25,250,'a'),
(26,260,'b'),
(27,270,'a'),
(28,280,'b'),
(29,290,'b'),
(30,300,'a'),
(31,310,'a'),
(32,320,'c'),
(33,330,'d'),
(34,340,'b'),
(35,350,'a');

--Tema 3 Fenómemos Físicos y Químicos
INSERT INTO RespuestasQ1 VALUES (36,360,'a'),
(37,370,'a'),
(38,380,'c'),
(39,390,'c'),
(40,400,'a'),
(41,410,'a'),
(42,420,'c'),
(43,430,'c'),
(44,440,'b'),
(45,450,'a'),
(46,460,'a'),
(47,470,'a'),
(48,480,'a'),
(49,490,'b'),
(50,500,'a'),
(51,510,'b'),
(52,520,'a'),
(53,530,'b'),
(54,540,'a'),
(55,550,'c'),
(56,560,'d'),
(57,570,'c'),
(58,580,'b'),
(59,590,'b'),
(60,600,'b');

--Tema 4 Elemento, Compuesto y Mezcla
INSERT INTO RespuestasQ1 VALUES (61,610,'a'),
(62,620,'c'),
(63,630,'a'),
(64,640,'a'),
(65,650,'a'),
(66,660,'c'),
(67,670,'a'),
(68,680,'b'),
(69,690,'c'),
(70,700,'b'),
(71,710,'a'),
(72,720,'b'),
(73,730,'c'),
(74,740,'b'),
(75,750,'b'),
(76,760,'a'),
(77,770,'b'),
(78,780,'a'),
(79,790,'b'),
(80,800,'a'),
(81,810,'a'),
(82,820,'b'),
(83,830,'b'),
(84,840,'a'),
(85,850,'b');

--Tema 5 Métodos de Separación de Mezclas
INSERT INTO RespuestasQ1 VALUES (86,860,'b'),
(87,870,'b'),
(88,880,'c'),
(89,890,'c'),
(90,900,'c'),
(91,910,'c'),
(92,920,'a'),
(93,930,'c'),
(94,940,'c'),
(95,950,'c'),
(96,960,'c'),
(97,970,'b'),
(98,980,'c'),
(99,990,'b'),
(100,1000,'a'),
(101,1010,'a'),
(102,1020,'a'),
(103,1030,'b'),
(104,1040,'a'),
(105,1050,'b'),
(106,1060,'c'),
(107,1070,'b'),
(108,1080,'b'),
(109,1090,'b'),
(110,1100,'c');

--Respuestas Segundo Parcial Química 1

--Tema 1 El Átomo
INSERT INTO RespuestasQ1 VALUES (111,1110,'a'),
(112,1120,'b'),
(113,1130,'b'),
(114,1140,'b'),
(115,1150,'a'),
(116,1160,'c'),
(117,1170,'b'),
(118,1180,'c'),
(119,1190,'a'),
(120,1200,'a'),
(121,1210,'a'),
(122,1220,'a'),
(123,1230,'c'),
(124,1240,'b'),
(125,1250,'c'),
(126,1260,'c'),
(127,1270,'a'),
(128,1280,'b'),
(129,1290,'a'),
(130,1300,'b'),
(131,1310,'c'),
(132,1320,'a'),
(133,1330,'c'),
(134,1340,'b'),
(135,1350,'b');

--Tema 2 Números Cuánticos
INSERT INTO RespuestasQ1 VALUES (136,1360,'a'),
(137,1370,'b'),
(138,1380,'c'),
(139,1390,'a'),
(140,1400,'c'),
(141,1410,'a'),
(142,1420,'c'),
(143,1430,'c'),
(144,1440,'a'),
(145,1450,'c'),
(146,1460,'b'),
(147,1470,'a'),
(148,1480,'a'),
(149,1490,'b'),
(150,1500,'b'),
(151,1510,'c'),
(152,1520,'b'),
(153,1530,'a'),
(154,1540,'b'),
(155,1550,'a'),
(156,1560,'c'),
(157,1570,'b'),
(158,1580,'c'),
(159,1590,'c'),
(160,1600,'a');

--Tema 3 Tabulación de los Números Cuánticos
INSERT INTO RespuestasQ1 VALUES (161,1610,'c'),
(162,1620,'a'),
(163,1630,'d'),
(164,1640,'b'),
(165,1650,'b'),
(166,1660,'c'),
(167,1670,'a'),
(168,1680,'d'),
(169,1690,'c'),
(170,1700,'d'),
(171,1710,'c'),
(172,1720,'a'),
(173,1730,'b'),
(174,1740,'b'),
(175,1750,'c'),
(176,1760,'a'),
(177,1770,'d'),
(178,1780,'a'),
(179,1790,'c'),
(180,1800,'b'),
(181,1810,'d'),
(182,1820,'a'),
(183,1830,'c'),
(184,1840,'b');

--Tema 4 Principio de Construcción o Aufbau
INSERT INTO RespuestasQ1 VALUES (185,1850,'b'),
(186,1860,'c'),
(187,1870,'b'),
(188,1880,'c');

--Tema 5 Configuración Electrónica
INSERT INTO RespuestasQ1 VALUES (189,1890,'b'),
(190,1900,'a'),
(191,1910,'a'),
(192,1920,'c'),
(193,1930,'c'),
(194,1940,'b'),
(195,1950,'a'),
(196,1960,'c'),
(197,1970,'b'),
(198,1980,'b'),
(199,1990,'a'),
(200,2000,'c'),
(201,2010,'a');

--Tema 6 Construcción de la Tabla Periódica
INSERT INTO RespuestasQ1 VALUES (202,2020,'a'),
(203,2030,'a'),
(204,2040,'b'),
(205,2050,'c'),
(206,2060,'b'),
(207,2070,'b'),
(208,2080,'a'),
(209,2090,'a'),
(210,2100,'a'),
(211,2110,'a'),
(212,2120,'a'),
(213,2130,'b'),
(214,2140,'c');

--Tema 7 Propiedades Periódicas
INSERT INTO RespuestasQ1 VALUES (215,2150,'c'),
(216,2160,'a'),
(217,2170,'a'),
(218,2180,'a'),
(219,2190,'b'),
(220,2200,'b'),
(221,2210,'b'),
(222,2220,'a'),
(223,2230,'c'),
(224,2240,'b'),
(225,2250,'a'),
(226,2260,'b'),
(227,2270,'c');

--Tema 8 Propiedades de los Elementos de Transición
INSERT INTO RespuestasQ1 VALUES (228,2280,'b'),
(229,2290,'b'),
(230,2300,'b'),
(231,2310,'c'),
(232,2320,'b');

--Respuestas Tercer Parcial Química 1

--Tema 1 Enlace Químico 
INSERT INTO RespuestasQ1 VALUES (233,2330,'b'),
(234,2340,'b'),
(235,2350,'a'),
(236,2360,'a'),
(237,2370,'a'),
(238,2380,'b'),
(239,2390,'a'),
(240,2400,'b'),
(241,2410,'a'),
(242,2420,'a'),
(243,2430,'b'),
(244,2440,'a'),
(245,2450,'a'),
(246,2460,'a'),
(247,2470,'c'),
(248,2480,'a'),
(249,2490,'b'),
(250,2500,'c'),
(251,2510,'a'),
(252,2520,'d'),
(253,2530,'b'),
(254,2540,'b'),
(255,2550,'b'),
(256,2560,'a'),
(257,2570,'c'),
(258,2580,'c'),
(259,2590,'c'),
(260,2600,'b'),
(261,2610,'a'),
(262,2620,'b'),
(263,2630,'b'),
(264,2640,'c'),
(265,2650,'a'),
(266,2660,'b'),
(267,2670,'a'),
(268,2680,'c'),
(269,2690,'b'),
(270,2700,'a'),
(271,2710,'b'),
(272,2720,'a'),
(273,2730,'a'),
(274,2740,'a'),
(275,2750,'a'),
(276,2760,'a'),
(277,2770,'b'),
(278,2780,'a'),
(279,2790,'c'),
(280,2800,'b'),
(281,2810,'c'),
(282,2820,'b'),
(283,2830,'a'),
(284,2840,'b'),
(285,2850,'a'),
(286,2860,'b'),
(287,2870,'b'),
(288,2880,'b'),
(289,2890,'a'),
(290,2900,'a'),
(291,2910,'a'),
(292,2920,'a'),
(293,2930,'b'),
(294,2940,'b'),
(295,2950,'b'),
(296,2960,'b');

--Tema 2 Nomenclatura Química Inorgánica
INSERT INTO RespuestasQ1 VALUES (297,2970,'a'),
(298,2980,'b'),
(299,2990,'c'),
(300,3000,'a'),
(301,3010,'a'),
(302,3020,'a'),
(303,3030,'b'),
(304,3040,'c'),
(305,3050,'c'),
(306,3060,'b'),
(307,3070,'a'),
(308,3080,'c'),
(309,3090,'a'),
(310,3100,'c'),
(311,3110,'a'),
(312,3120,'c'),
(313,3130,'b'),
(314,3140,'a'),
(315,3150,'c'),
(316,3160,'a'),
(317,3170,'a'),
(318,3180,'b');

--Tema 3 Hidruros Metálicos
INSERT INTO RespuestasQ1 VALUES (319,3190,'c'),
(320,3200,'a'),
(321,3210,'c'),
(322,3220,'b'),
(323,3230,'b'),
(324,3240,'b'),
(325,3250,'b'),
(326,3260,'b'),
(327,3270,'b'),
(328,3280,'b'),
(329,3290,'a'),
(330,3300,'c'),
(331,3310,'c'),
(332,3320,'c'),
(333,3330,'b'),
(334,3340,'a');

--Tema 4 Hidruros no Metálicos – Ácidos
INSERT INTO RespuestasQ1 VALUES (335,3350,'a'),
(336,3360,'a'),
(337,3370,'b'),
(338,3380,'c'),
(339,3390,'b'),
(340,3400,'b'),
(341,3410,'c'),
(342,3420,'a'),
(343,3430,'a'),
(344,3440,'a'),
(345,3450,'a'),
(346,3460,'a'),
(347,3470,'a');

--Tema 5 Sales Binarias
INSERT INTO RespuestasQ1 VALUES (348,3480,'b'),
(349,3490,'a'),
(350,3500,'b'),
(351,3510,'c'),
(352,3520,'a'),
(353,3530,'b'),
(354,3540,'c'),
(355,3550,'a'),
(356,3560,'b'),
(357,3570,'a'),
(358,3580,'b'),
(359,3590,'a'),
(360,3600,'a'),
(361,3610,'a'),
(362,3620,'a'),
(363,3630,'b');

--Tema 6 Hidróxidos
INSERT INTO RespuestasQ1 VALUES (364,3640,'d'),
(365,3650,'a'),
(366,3660,'b'),
(367,3670,'b'),
(368,3680,'b'),
(369,3690,'c'),
(370,3700,'b'),
(371,3710,'a'),
(372,3720,'b'),
(373,3730,'b'),
(374,3740,'a'),
(375,3750,'a'),
(376,3760,'a'),
(377,3770,'c'),
(378,3780,'a'),
(379,3790,'a'),
(380,3800,'a');